# Generated by Django 4.1.4 on 2022-12-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrozamin_hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Shahar', 'verbose_name_plural': 'Shaharlar'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Tuman', 'verbose_name_plural': 'Tumanlar'},
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='extra_skill',
            field=models.ManyToManyField(blank=True, to='agrozamin_hr.extracategory'),
        ),
    ]
