# Generated by Django 4.1.4 on 2023-01-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrozamin_hr', '0002_alter_city_options_alter_region_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='city',
        ),
        migrations.RemoveField(
            model_name='extraquestion',
            name='ans_ru',
        ),
        migrations.RemoveField(
            model_name='extraquestion',
            name='ans_uz',
        ),
        migrations.RemoveField(
            model_name='extraquestion',
            name='extra_category_ru',
        ),
        migrations.RemoveField(
            model_name='extraquestion',
            name='extra_category_uz',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ans_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ans_uz',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category_uz',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='test_result',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='full_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
