# Generated by Django 4.1.4 on 2023-01-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrozamin_hr', '0003_remove_region_city_remove_extraquestion_ans_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='cv',
            field=models.FileField(blank=True, upload_to='cv_files'),
        ),
    ]
