# Generated by Django 4.1.4 on 2023-01-05 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrozamin_hr', '0006_userresults'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserResults',
            new_name='UserResult',
        ),
    ]
