# Generated by Django 4.1.4 on 2023-01-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('agrozamin_hr', '0007_rename_userresults_userresult'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_admin',
            new_name='Admin',
        ),
    ]
