# Generated by Django 4.1.4 on 2023-01-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrozamin_hr', '0009_rename_admin_user_admin'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user_admin',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user_admin',
            name='username',
        ),
        migrations.AddField(
            model_name='user_admin',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_admin',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user_admin',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
