# Generated by Django 4.1.4 on 2023-01-06 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrozamin_hr', '0011_alter_user_admin_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name_uz',
        ),
    ]
