# Generated by Django 4.1.4 on 2023-01-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrozamin_hr', '0012_remove_category_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extracategory',
            name='extra_category_name_ru',
        ),
        migrations.RemoveField(
            model_name='extracategory',
            name='extra_category_name_uz',
        ),
    ]
