# Generated by Django 4.1.4 on 2023-01-06 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrozamin_hr', '0013_remove_extracategory_extra_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserResult',
            new_name='QuetionResult',
        ),
        migrations.CreateModel(
            name='ExtraQuetionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField()),
                ('extra_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrozamin_hr.extraquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrozamin_hr.usermodel')),
            ],
        ),
    ]
