# Generated by Django 4.1.4 on 2023-01-10 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrozamin_hr', '0016_usermodel_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrozamin_hr.usermodel')),
            ],
            options={
                'verbose_name': 'SMS',
                'verbose_name_plural': 'SMSlar',
            },
        ),
    ]
