# Generated by Django 4.1.4 on 2023-01-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrozamin_hr', '0017_smshistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smshistory',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
