# Generated by Django 4.1.4 on 2023-01-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrozamin_hr', '0020_alter_smshistory_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smshistory',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
