# Generated by Django 4.1.4 on 2023-01-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrozamin_hr', '0028_alter_number_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='first_name',
            field=models.CharField(default='Durdona', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='number',
            name='last_name',
            field=models.CharField(default='HR', max_length=20),
            preserve_default=False,
        ),
    ]
