"""
Django settings for conf project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9r=j!4&oz!(4bsuhz=d1^^rj=4695((6xxoaz)^wj*l#w2+s8x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# ALLOWED_HOSTS = ['139.162.159.187', '127.0.0.1', 'jobir.uz']
ALLOWED_HOSTS = ["*"]

# AUTH_USER_MODEL = 'agrozamin_hr.UserModel'

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #language setting
    'modeltranslation',
    'django.contrib.admin',

    #app
    'agrozamin_hr',

    #django-rest
    'drf_yasg',
    'rest_framework',

    #admin customization
    'nested_admin',
    'admin_reorder',
    'location_field.apps.DefaultConfig',
]


AUTH_USER_MODEL = 'agrozamin_hr.User_admin'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', #for language
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'admin_reorder.middleware.ModelAdminReorder', #'admin reorder
]


ADMIN_REORDER = (
    # First group: Category and Question models
    {'app': 'agrozamin_hr', 'label': _('Kategoriya va savollar'),
     'models': ('agrozamin_hr.Category', 'agrozamin_hr.Question',)
    },

    # Second group: ExtraCategory and ExtraQuestion models
    {'app': 'agrozamin_hr', 'label': _("Qo'shimcha kategoriya va qo'shimcha savollar"),
     'models': ('agrozamin_hr.ExtraCategory', 'agrozamin_hr.ExtraQuestion',)
    },
    
    # third group: UserModel, QuetionResult, ExtraQuetionResult
    {'app': 'agrozamin_hr', 'label': _("Kandedatlar malumotlari"),
     'models': ('agrozamin_hr.UserModel',)
    },
    
    # fourth group: UserModel, QuetionResult, ExtraQuetionResult
    {'app': 'agrozamin_hr', 'label': _("Adminstratorlar malumotlari"),
     'models': ('agrozamin_hr.User_admin', 'agrozamin_hr.Address', 'agrozamin_hr.Number')
    },)


ROOT_URLCONF = 'conf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(BASE_DIR.joinpath('templates'))],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'conf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases



DATABASES = {
   'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('POSTGRES_DB'), 
        'USER': os.environ.get('POSTGRES_USER'), 
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': os.environ.get('POSTGRES_HOST'),    
        'PORT': os.environ.get('POSTGRES_PORT')
   }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/



#language settings
LANGUAGE_CODE = 'uz-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LANGUAGES = (
    ('ru','Russian'),
    ('uz','Uzbek'),
)
MODELTRANSLATION_LANGUAGES = ('ru', 'uz')

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = str(BASE_DIR.joinpath('static'))
STATICFILES_DIRS = []

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ADMINS = (
    ('hr-admin', 'jobirumirovmoliya@gmail.com'),
)
