# Generated by Django 4.1.4 on 2022-12-26 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_name_ru', models.CharField(max_length=200, null=True)),
                ('category_name_uz', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ExtraCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_category_name', models.CharField(max_length=200)),
                ('extra_category_name_ru', models.CharField(max_length=200, null=True)),
                ('extra_category_name_uz', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Extra category',
                'verbose_name_plural': 'Extra categories',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_ru', models.TextField(null=True)),
                ('question_uz', models.TextField(null=True)),
                ('A', models.CharField(max_length=200, null=True)),
                ('A_ru', models.CharField(max_length=200, null=True)),
                ('A_uz', models.CharField(max_length=200, null=True)),
                ('B', models.CharField(max_length=200, null=True)),
                ('B_ru', models.CharField(max_length=200, null=True)),
                ('B_uz', models.CharField(max_length=200, null=True)),
                ('C', models.CharField(max_length=200, null=True)),
                ('C_ru', models.CharField(max_length=200, null=True)),
                ('C_uz', models.CharField(max_length=200, null=True)),
                ('D', models.CharField(max_length=200, null=True)),
                ('D_ru', models.CharField(max_length=200, null=True)),
                ('D_uz', models.CharField(max_length=200, null=True)),
                ('ans', models.CharField(max_length=200, null=True)),
                ('ans_ru', models.CharField(max_length=200, null=True)),
                ('ans_uz', models.CharField(max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrozamin_hr.category')),
                ('category_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agrozamin_hr.category')),
                ('category_uz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agrozamin_hr.category')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='ExtraQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_ru', models.TextField(null=True)),
                ('question_uz', models.TextField(null=True)),
                ('A', models.CharField(max_length=200, null=True)),
                ('A_ru', models.CharField(max_length=200, null=True)),
                ('A_uz', models.CharField(max_length=200, null=True)),
                ('B', models.CharField(max_length=200, null=True)),
                ('B_ru', models.CharField(max_length=200, null=True)),
                ('B_uz', models.CharField(max_length=200, null=True)),
                ('C', models.CharField(max_length=200, null=True)),
                ('C_ru', models.CharField(max_length=200, null=True)),
                ('C_uz', models.CharField(max_length=200, null=True)),
                ('D', models.CharField(max_length=200, null=True)),
                ('D_ru', models.CharField(max_length=200, null=True)),
                ('D_uz', models.CharField(max_length=200, null=True)),
                ('ans', models.CharField(max_length=200, null=True)),
                ('ans_ru', models.CharField(max_length=200, null=True)),
                ('ans_uz', models.CharField(max_length=200, null=True)),
                ('extra_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrozamin_hr.extracategory')),
                ('extra_category_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agrozamin_hr.extracategory')),
                ('extra_category_uz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agrozamin_hr.extracategory')),
            ],
            options={
                'verbose_name': 'Extra question',
                'verbose_name_plural': 'Extra questions',
            },
        ),
    ]
